"""city_nullable_false

Revision ID: dab90787a15a
Revises: c3ef20032110
Create Date: 2024-10-10 22:49:49.583903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dab90787a15a"
down_revision: Union[str, None] = "c3ef20032110"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("city", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "city",
        "latitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "city",
        "longitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "city",
        "longitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "city",
        "latitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("city", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
